site_name: "Ryan's Blog"
pages:
    - INDEX: index.md
    - WELCOME:
        - Hello World! : helloworld.md
        - Setting Up My First Blog: set_steps.md
        - Helloworld again!: hello_world_again.md
    - PROJECTS:
        - Smart Home: projects/smarthome.md
        - Client Page: projects/client_page.md
        - Ryan's IM: projects/ryan-im.md
    - WEB:
        - HOW TO RUN DEBUG SERVER: at_company/debug_instructions.md
        - HTTP Protocol: at_company/about_http.md
        - My First Flask Program: at_company/flask_demo.md
        - DATABASE: at_company/about_db.md
        - EXPERIENCES: at_company/develop_experiences.md
        - SQLAlchemy: at_company/about_sqlalchemy.md
        - DOCKER: at_company/docker.md
        - JQUERY: at_company/jquery.md
        - CSS: at_company/css.md
        - NODE: at_company/node.md
        - Nginx: at_company/nginx.md
        - PHP: at_company/php.md
    - LINUX HACKING:
        - BUILD A KERNEL FROM SOURCE: linux/build_from_source.md
        - ADD A HELLOWORLD SYSTEM CALL: linux/system_call.md
        - USE LKM TO ADD A SYSCALL: linux/LKM_system_call.md
    - SUMMARIES:
        - WHEN AM TEMPORARILY AWAY FROM WEB: at_company/ideas.md
        - LINUX INSTRUCTIONS: summeries/instructions_in_linux.md
    - TOOLS:
        - Git: at_company/git_instructions.md
        - VPN: at_company/steps_to_build_vpn.md
        - HOTKEYS: at_company/about_hotkeys.md
    - README: readme.md
theme_dir: ./theme
