site_name: "Ryan's Blog"
pages:
    - Index: index.md
    - Hello My Blog:
        - Hello World! : helloworld.md
        - Setting Up My First Blog: set_steps.md
        - Helloworld again!: hello_world_again.md
    - Technical Summeries:
        - Instrutions Summeries In Linux: summeries/instructions_in_linux.md
    - At Company:
        - How to start the debug server: at_company/debug_instructions.md
    - README: readme.md
theme: slate
